baseURL: "https://JXSnack.github.io"
languageCode: "en-us"
theme: "PaperMod"

paginate: 5  # 5 Postings pro Seite
enableRobotsTXT: true

minify:
  disable: false
  minifyOutput: true

params:
  env: production
  title: "Snackbag.net - The Blog"
  description: "A trial of errors"
  keywords:
    - Blog
    - JXSNack
  author: JX_Snack@gmail.com
  DateFormat: "Jan 2, 2006"
  defaultTheme: "light"
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true

  editPost:
    URL: "https://github.com/JXSnack/JXSnack.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: true
    style: friendly
